POST http://localhost:3003/user/create
Content-Type: application/json

{
    "name":"Victoria",
    "email":"vicksout@gmail.com",
    "password":"vick1234"
}

###

GET http://localhost:3003/user/all


###

GET http://localhost:3003/user/get/2d1fb991-c0bf-4942-b033-50527a9d00ee

###

POST http://localhost:3003/post/create
Content-Type: application/json

{
    "photo":"https://www.zooplus.pt/magazine/wp-content/uploads/2021/03/kitten-sitzt-boden-768x512-1.jpeg",
    "description":"Teste gatinho fofo",
    "type":"normal",
    "authorId":"2d1fb991-c0bf-4942-b033-50527a9d00ee"
}

###

GET http://localhost:3003/post/get/4be3cbe4-571b-449d-9140-7b6f799ff7fb

###

GET http://localhost:3003/post/all

###

GET http://localhost:3003/post/feed/2d1fb991-c0bf-4942-b033-50527a9d00ee

###

GET http://localhost:3003/friends/all

###


POST http://localhost:3003/friends/create 
Content-Type: application/json

{
    "fkUser1":"2d1fb991-c0bf-4942-b033-50527a9d00ee",
    "fkUser2":"ef5f5a71-52c1-4178-aae2-d2b996bc72be"
}

###

GET http://localhost:3003/friends/ef5f5a71-52c1-4178-aae2-d2b996bc72be

###

DELETE http://localhost:3003/friends/399344cd-346a-440d-8b-82cc64404f34